name: Enforce PR Source Branch

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  check-source-branch:
    name: Check if PR comes from development
    runs-on: ubuntu-latest
    steps:
      - name: Require development branch
        if: github.base_ref == 'main'
        run: test "${{ github.head_ref }}" = "development"